#Prompt để tạo data sample trò chuyện
"""
Bạn là trợ lý AI tạo dữ liệu hội thoại tự nhiên.  
Hãy tạo 100 câu nói của người dùng mang tính trò chuyện, xã giao hoặc bộc lộ cảm xúc,  
không liên quan đến sản phẩm hoặc mua hàng.  

Bao gồm:
- Câu chào hỏi, bắt chuyện
- Câu hỏi về cảm xúc, thời tiết, sở thích
- Câu giới thiệu bản thân
- Câu chia sẻ tâm trạng
- Câu mời trò chuyện

Yêu cầu:
- Câu nói tự nhiên, ngắn gọn, thân mật như người Việt Nam thật.
- Một số câu có thể có tên riêng hoặc địa điểm.
- Kết quả trả về là một danh sách Python tên `chitchatSample = [...]`

"""
chitchatSample = [
    "Nhắc lại tên tôi",
    "Nhắc lại tên tôi 3 lần",
    "Giá vàng hôm nay bao nhiêu ta?",
    "Không biết giá vàng hôm nay sao rồi",
    "Giá vàng hôm nay",
    "Giá xăng tăng hay giảm?",
    "Chào bạn, hôm nay khỏe không?",
    "Hi, dạo này bạn bận không?",
    "Trời hôm nay mát thật ha!",
    "Bạn đang làm gì đó?",
    "Nghe nói Sài Gòn mưa suốt tuần này luôn hả?",
    "Tôi mới dậy nè, còn bạn?",
    "Bạn có hay nghe nhạc không?",
    "Tối nay bạn có kế hoạch gì chưa?",
    "Tôi đang hơi chán, nói chuyện với tôi đi.",
    "Sáng nay cà phê chưa?",
    "Xin chào, rất vui được gặp bạn!",
    "Hôm nay bạn thấy thế nào?",
    "Ủa, bạn ở Hà Nội hả?",
    "Bạn thích ăn món gì nhất?",
    "Mệt quá trời luôn, bạn thì sao?",
    "Tôi tên Thịnh, còn bạn tên gì?",
    "Trưa nay ăn gì ngon chưa?",
    "Bạn có nuôi thú cưng không?",
    "Hôm nay đẹp trời ghê!",
    "Trời lạnh quá, bạn có ra đường không?",
    "Mới đi học về, mệt mà vui.",
    "Tối nay bạn rảnh không, tám chút đi.",
    "Nghe nói mai mưa to lắm.",
    "Bạn thích đi du lịch không?",
    "Tôi vừa xem phim xong, hay lắm!",
    "Có khi nào bạn thấy nhớ ai mà không biết tại sao không?",
    "Buổi sáng của bạn thường bắt đầu thế nào?",
    "Tôi hơi buồn ngủ, nhưng vẫn muốn nói chuyện.",
    "Bạn có thích đọc sách không?",
    "Trưa nay nắng gắt ghê luôn!",
    "Bạn đang ở nhà hay ở chỗ làm vậy?",
    "Thứ Bảy rồi, vui quá trời!",
    "Tôi đang nghe nhạc chill, dễ chịu lắm.",
    "Bạn có thích chạy bộ không?",
    "Dạo này bạn ngủ đủ giấc không?",
    "Tôi đang ngồi ngắm mưa nè.",
    "Bạn có hay đi cà phê với bạn bè không?",
    "Trời ơi, hôm nay nóng muốn xỉu luôn!",
    "Bạn có xem bóng đá không?",
    "Sáng nay bạn dậy sớm không?",
    "Tôi mới đi làm về, hơi mệt xíu.",
    "Bạn có hay online không?",
    "Tôi thích trời mưa nhẹ, bạn thì sao?",
    "Bạn có thích xem phim không?",
    "Tôi đang suy nghĩ linh tinh, muốn nói chuyện chút.",
    "Hôm nay của bạn ổn chứ?",
    "Bạn có anh chị em không?",
    "Lâu rồi không nói chuyện với ai, thấy hơi buồn.",
    "Trời âm u quá, buồn ngủ ghê.",
    "Bạn đang nghe nhạc gì đó?",
    "Hôm nay đi làm có vui không?",
    "Bạn có thích đồ ăn cay không?",
    "Nghe giọng bạn chắc người miền Nam ha?",
    "Tôi đang ở Đà Lạt, trời lạnh quá trời luôn!",
    "Bạn có hay dùng mạng xã hội không?",
    "Tôi mới tập thể dục xong, thấy khỏe ghê.",
    "Bạn có thường xuyên nấu ăn không?",
    "Chiều nay đi dạo không?",
    "Tôi thấy hơi cô đơn, bạn có khi nào vậy không?",
    "Bạn có hay đi xem phim không?",
    "Thời tiết kiểu này chỉ muốn nằm ngủ thôi.",
    "Bạn có thích mùa thu không?",
    "Tôi đang làm bài tập mà lười quá.",
    "Bạn có đang học gì mới không?",
    "Tối nay ăn gì ngon chưa?",
    "Tôi thấy nhớ nhà quá.",
    "Bạn có thích đi biển không?",
    "Hôm nay trời dễ chịu ghê.",
    "Tôi đang làm việc ở quán cà phê, chill lắm.",
    "Bạn có hay thức khuya không?",
    "Mấy hôm nay ngủ không ngon gì cả.",
    "Bạn có thích mèo hay chó hơn?",
    "Tôi đang coi lại phim cũ, nhớ ghê.",
    "Bạn có hay đi chơi cuối tuần không?",
    "Trưa nay ăn cơm hay ăn mì vậy?",
    "Hôm nay bạn vui không?",
    "Tôi đang rảnh quá nên muốn tám tí.",
    "Bạn có thích đi xem ca nhạc không?",
    "Tôi mới gặp lại bạn cũ, vui dã man.",
    "Bạn có khi nào thấy thời gian trôi nhanh ghê không?",
    "Tôi đang uống trà sữa, bạn có thích không?",
    "Bạn làm việc ở đâu vậy?",
    "Nghe nhạc buồn mà thấy dễ chịu ghê.",
    "Tối nay trăng sáng đẹp quá.",
    "Bạn có thích đi leo núi không?",
    "Tôi đang nằm nghe podcast nè.",
    "Bạn có đang yêu ai không?",
    "Trưa nay nắng như đổ lửa luôn!",
    "Tôi đang định học thêm kỹ năng mới.",
    "Bạn có từng đi Đà Nẵng chưa?",
    "Mấy nay tâm trạng tôi hơi chùng.",
    "Bạn có thích uống cà phê sữa đá không?",
    "Tôi mới về quê chơi, vui lắm luôn.",
    "Bạn có thích ăn vặt không?",
    "Hôm nay tôi thấy khá hơn rồi.",
    "Bạn có hay gọi điện cho bạn bè không?",
    "Tôi đang nghĩ về tương lai, hơi lo chút.",
    "Bạn có thích làm việc nhóm không?",
    "Trời vừa tạnh mưa, mát ghê.",
    "Tôi mới dọn phòng xong, gọn gàng hẳn!",
    "Bạn có thích nghe nhạc lo-fi không?",
    "Tôi đang cảm thấy khá vui hôm nay.",
    "Bạn rảnh thì nói chuyện chơi nha!"
]
